spring.application.name = rentsandclients
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/rentsAndClients?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=dsds

# Configurações do Hibernate (JPA)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# Opcional: Configurações adicionais
spring.jpa.properties.hibernate.format_sql=true
